version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ccontrol-m-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - ccontrol-network
    # Volumes para desenvolvimento (comentado para produção)
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf
    #   - ./dist:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Descomente esta seção se você quiser rodar a API no mesmo compose
  # api:
  #   image: ccontrol-m-api:latest
  #   container_name: ccontrol-m-api
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DATABASE_URL=postgresql://user:password@postgres:5432/ccontrol
  #     - JWT_SECRET=seu_jwt_secret_seguro
  #   networks:
  #     - ccontrol-network
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped

  # postgres:
  #   image: postgres:14-alpine
  #   container_name: ccontrol-postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=ccontrol
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - ccontrol-network
  #   restart: unless-stopped

networks:
  ccontrol-network:
    driver: bridge

# volumes:
#   postgres_data: 