version: '3.8'

services:
  # Serviço do Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ccontrol-m-backend
    restart: unless-stopped
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=production
      - API_PREFIX=/api/v1
      - BACKEND_CORS_ORIGINS=http://localhost,http://frontend
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - ccontrol-network

  # Serviço do Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8002/api/v1
        - VITE_MOCK_ENABLED=false
    container_name: ccontrol-m-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ccontrol-network

networks:
  ccontrol-network:
    driver: bridge 