global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ccontrol_backend"
    metrics_path: "/api/v1/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ["backend:8000"]
        labels:
          service: "ccontrol-backend"
          environment: "production"

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
        labels:
          service: "postgres"
          environment: "production"

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
        labels:
          service: "redis"
          environment: "production"

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          service: "host-metrics"
          environment: "production" 